#!/bin/sh /etc/rc.common
# Copyright (C) 2026 OpenWrt.org

START=90
STOP=10

USE_PROCD=1
PROG=/usr/bin/headscale
CONF_SCRIPT=/usr/share/headscale/headscale.sh
CONF_FILE=/var/etc/headscale/config.yaml

start_service() {
	local enabled

	config_load headscale
	config_get_bool enabled server enabled 0

	[ "$enabled" -eq 1 ] || return 0

	# Generate config.yaml
	if [ -x "$CONF_SCRIPT" ]; then
		"$CONF_SCRIPT" || return 1
	fi

	[ -f "$CONF_FILE" ] || return 1

	procd_open_instance headscale
	procd_set_param command "$PROG" serve -c "$CONF_FILE"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /etc/config/headscale
	procd_set_param limits core="unlimited"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "headscale"
}

reload_service() {
	stop
	start
}
